export const SIGN_IN_REQUEST = '@auth/SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = '@auth/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = '@auth/SIGN_IN_FAILURE';

export const SIGN_UP_REQUEST = '@auth/SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = '@auth/SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = '@auth/SIGN_UP_FAILURE';

export const GET_COMMENTS_REQUEST = '@comments/GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = '@comments/GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = '@comments/GET_COMMENTS_FAILURE';

export const ADD_COMMENT_REQUEST = '@comments/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = '@comments/ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = '@comments/ADD_COMMENT_FAILURE';

export const GET_NOTIFICATIONS_REQUEST =
  '@notifications/GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS =
  '@notifications/GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE =
  '@notifications/GET_NOTIFICATIONS_FAILURE';

export const CONFIRM_NOTIFICATIONS_REQUEST =
  '@notifications/CONFIRM_NOTIFICATIONS_REQUEST';
export const CONFIRM_NOTIFICATIONS_SUCCESS =
  '@notifications/CONFIRM_NOTIFICATIONS_SUCCESS';
export const CONFIRM_NOTIFICATIONS_FAILURE =
  '@notifications/CONFIRM_NOTIFICATIONS_FAILURE';
